### ISSUE TITLE
Error Snscraper

### ISSUE THREAD

**Issue by Rana-0003** [steevenakintilo/TwitterGiveawayBot#1]
I did unzip cromedriver file and move it to Twitter giveaway directory and also did pip install snscraper.

Help me out if i did any mistake, i'm getting this error : 

Error Unable to find guest token 
Traceback (most recent call last):
    File "E:\TwitterGiveawayBot-main\get_tweet.py", line 282, in search giveaway
        For i,tweet in enumerate(sntwitter.TwitterSearchScraper(text).get_items() ):
    File "C:\Users\Max\AppData\Local\Programs\Python36\lib\site.packages\snscrape\modules\twitter.py", line 131, in get_items
        guestToken = self._get_guest_token()
    File "C:\Users\Max\AppData\Local\Programs\Python36\lib\site.packages\snscrape\modules\twitter.py", line 109, in _get_guest_token
        raise snscrape.base.ScraperExecption('Unable to find guest token')
snscrape.base.ScraperExecption: Unable to find guest token

**Comment by steevenakintilo** [comment]
Oh never got this error but it's seems the error come from snscrape.
Could you do pip list command 
And tell me the version of sncrape ?

**Comment by Rana-0003** [comment]
This is my pip list (some of them are previously installed) :- 
PS C:\Windows\system32> pip list
Package            Version
------------------ -----------
beautifulsoup4     4.12.2
certifi            2022.12.7
charset-normalizer 2.0.12
emoji              2.5.1
feedparser         6.0.10
future             0.18.3
idna               3.4
lxml               4.9.2
oauthlib           3.2.2
pip                21.3.1
PySocks            1.7.1
python-dateutil    2.8.2
python-twitter     3.5
PyYAML             6.0
requests           2.27.1
requests-oauthlib  1.3.1
selenium           3.141.0
setuptools         28.8.0
sgmllib3k          1.0.0
six                1.16.0
snscrape           0.3.4
soupsieve          2.3.2.post1
tweepy             1.7.1
twitter            1.19.6
urllib3            1.26.14

I got it now my snscrape is old version 0.3.4, latest version is  0.6.2.20230320 but i did install latest version with pip install snscrape command, why it didn't work? 

Thanks for the help !!!

**Comment by steevenakintilo** [comment]
Did it worked ?
If no try this command https://github.com/JustAnotherArchivist/snscrape.git
And retry launching the program

**Comment by Rana-0003** [comment]
Issue was my python version was 3.6.0 so latest version of snscrape 0.6.2 couldn't be installed on lower 3.8 python version.

Thanks for the help!!!

**Comment by steevenakintilo** [comment]
Ok ok good then happy to have helped
