### ISSUE TITLE
Tagging and comment Issue

### ISSUE THREAD

**Issue by Rana-0003** [steevenakintilo/TwitterGiveawayBot#5]
In tag 2 - 3 people, only tagging one same person everytime. Random/different people tagging also not working, acting more like bot.

In comments not picking up exact words to comment.

**Comment by steevenakintilo** [comment]
First sentence: is it always @ the same person or always the same perons 
Could you give your twitter account name so I can see myself how it's doing
It's not doing random people the way it does is like this:

You add 3 @ to the configuration.yml file

If the bot need to tag 1 person it always @ the same if it need to tag 2 it will always @ the 2 person and the same for 3

For the comment is it cmmenting too much or too less???

But the comment part isn't 100% working sometimes it comments to word and sometimes not enough but that's because some people do their "tweet" not like the majority and I can't make an if for every type of tweet an user do

**Comment by Rana-0003** [comment]
It's always @ same person and for id, I've deleted all the comments. I'll run the bot again and will get back to you soon

**Comment by steevenakintilo** [comment]
Ok ok run again and give me your twitter @ so I can understand better

**Comment by Rana-0003** [comment]
Sorry for being this late, i was busy. My Id is @BlliOds and if you wanna skip going through my profile then direct search for @samiko whom i'm tagging in comments.

**Comment by steevenakintilo** [comment]
I see nothing :(![Screenshot_20230715-205347_Twitter.jpg](https://github.com/steevenakintilo/TwitterGiveawayBot/assets/72024403/891d1a9e-d2ec-4460-8ab7-675cccb4535a)

**Comment by Rana-0003** [comment]
Try @samiko then u'll see

**Comment by Rana-0003** [comment]
May be it's bcoz i changed my username. Try this link then
https://twitter.com/BlliOds?t=BNVlJB5tZYelCV391ocUgA&s=09

**Comment by steevenakintilo** [comment]
thanks

**Comment by steevenakintilo** [comment]
is that done by the bot ? 
![image](https://github.com/steevenakintilo/TwitterGiveawayBot/assets/72024403/4a2b47d7-8a23-446d-8a69-8335b8df0dbd)

**Comment by Rana-0003** [comment]
Yup that's done by bot

**Comment by steevenakintilo** [comment]
Ok I may know why it only tag 1 person show me what you get on the one_poeple_list two_poeple_list and three_or_more_poeple_list on the configuration.yml file

**Comment by Rana-0003** [comment]
# Word list to check if we need to tag 1 account
one_poeple_list:
  - "1"
  - "a person"
  - "a friend"
  - "1 person"
  - "1 friend"
  - "1 people"

# Word list to check if we need to tag 2 accounts
two_poeple_list:
  - "2"
  - "2 person"
  - "2 friends"
  - "2 people"

# Word list to check if we need to tag 3 accounts or more
three_or_more_poeple_list:
  - "3"
  - "3 person"
  - "3 friends"
  - "3 people"

**Comment by steevenakintilo** [comment]
ok thanks what about this word_list_to_check_for_tag? still on the config file

**Comment by Rana-0003** [comment]
word_list_to_check_for_tag:
  - "invite"
  - "mention"
  - "tag"

**Comment by steevenakintilo** [comment]
and accounts_to_tag?

**Comment by Rana-0003** [comment]
accounts_to_tag:
  
  - " @samiko "
  - "@bonima "
  - "@LucaPaulus40326 "
  - "@redsaw "
  - "@45Eds "
  - "@LeroyyNFT "
  - "@garryma "
  - "@Sizuhan "
  - "@maddygar "
  - "@RakulPreet5 "
  - "@JoshwaKing7277 "
  - "@DarvideVel52341 "
  - "@GarryMadgwick "

**Comment by steevenakintilo** [comment]
Ok let me try it myself then

**Comment by steevenakintilo** [comment]
I got it it's just because you put "1" on the one_people_list and the bot check if the element of the list is inside the string ex:

I got a new Ferrari if you add "fer" to the word to search it will find it since fer is inside ferrari

So it does same for the bot just remove the "1" ,"2","3" and all will be fine

**Comment by steevenakintilo** [comment]
You are really helpful to me with my bot thanks to you I added new "features" and fixed problem.

If you have any idea of "features" or "bug" to fix just tell me

**Comment by Rana-0003** [comment]
> I got it it's just because you put "1" on the one_people_list and the bot check if the element of the list is inside the string ex:
> 
> I got a new Ferrari if you add "fer" to the word to search it will find it since fer is inside ferrari
> 
> So it does same for the bot just remove the "1" ,"2","3" and all will be fine

So if i remove the 1-2-3 words from list and how will bot detect on giveaways that how many friends to tag in comments? For ex:- a giveaway ask to tag 2 friends and tag list look like this :-

one_poeple_list
"fri"

two_poeple_list
"frien"

three_poeple_list
"friends"

Whether it's fri -frien or friends, for bot these are same words leads to friends, so how's bot gonna detect that how many to tag, if giveaway ask to tag 2 friends??

**Comment by Rana-0003** [comment]
> You are really helpful to me with my bot thanks to you I added new "features" and fixed problem.
> 
> If you have any idea of "features" or "bug" to fix just tell me

Thanks It's just i really like what you've done with your bot here and i wanted it to be more better. Really appreciate your work and support ♥️

**Comment by steevenakintilo** [comment]
Like in this pic just add the 2 friends to the two_people_list and the bot will detect that you need to @ 2 people![Screenshot_20230716-215255_Twitter.jpg](https://github.com/steevenakintilo/TwitterGiveawayBot/assets/72024403/638369ec-50ff-4be8-903f-bb914441231f)

**Comment by steevenakintilo** [comment]
So your list was good just the remove the "1" "2" "3" from the list and keep the rest and it's fine

**Comment by steevenakintilo** [comment]
> > You are really helpful to me with my bot thanks to you I added new "features" and fixed problem.
> > 
> > If you have any idea of "features" or "bug" to fix just tell me
> 
> Thanks It's just i really like what you've done with your bot here and i wanted it to be more better. Really appreciate your work and support ♥️

Thanks 👌❤
I like the  bot I've made and I keep improving it everytime I see a problem or a feature to be added

**Comment by Rana-0003** [comment]
> So your list was good just the remove the "1" "2" "3" from the list and keep the rest and it's fine



So If i'm going to remove the 1" "2" "3" from tag list and then it's going to be look like this. 

one_poeple_list
"people"

two_poeple_list
"people"

three_poeple_list
"people"

See no difference then how's bot gonna detect that how many to tag??? 
If your answer still same, then may be i need to run bot and see to it for myself

**Comment by steevenakintilo** [comment]
Noo you are misunderstanding just do like that 
One_people_list:
1 person
1 friend 
1 user

Two_people_list:
2 person
2 friends
2 user

Same for 3 or more
And add more word if you see other word that come often when you need to tag 1 2 3 or more accounts

**Comment by Rana-0003** [comment]
> Noo you are misunderstanding just do like that One_people_list: 1 person 1 friend 1 user
> 
> Two_people_list: 2 person 2 friends 2 user
> 
> Same for 3 or more And add more word if you see other word that come often when you need to tag 1 2 3 or more accounts

Ok ok Now i got it thanks.
