### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by MrEnok94** [steevenakintilo/TwitterGiveawayBot#6]
Hello, I am noob with code so I have no Idea why it is not working. I can send you a screenshot if needed no problem and you can  find the error in the title of this thing. Goodbye

**Comment by steevenakintilo** [comment]
have you done pip install -r requirements.txt ?

**Comment by MrEnok94** [comment]
yes I did this command in the windows terminal.

**Comment by steevenakintilo** [comment]
Oh yeah share a pic or do you have discord ?

**Comment by MrEnok94** [comment]
discord please sorry for late response this is my discord MrEnok / mrenok

**Comment by steevenakintilo** [comment]
ok I will dm you on discord

**Comment by steevenakintilo** [comment]
Just asked for a friend request
